version: "3"
services:
  api:
    build: .
    image: institute
    ports:
      - "8080:8080"
  ui:
    image: nginx
    ports:
      - "81:81"
    volumes:
      - C:/Users/TRA0004/Documents/Front End Area/Full-Stack-TIC-TAC-TOE/UI:/usr/share/nginx/html
    depends_on:
      - api